"""Tests for dataset.list_models tool via MCP RPC layer.

Verifies the MCP-level list_models handler in mcp_rpc.py returns
the expected Markdown table format with model routing information.
"""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
from foggy.dataset_model.semantic.service import SemanticQueryService
from foggy.demo.models.ecommerce_models import create_fact_order_model, create_fact_sales_model
from foggy.mcp.routers.mcp_rpc import (
    create_mcp_router,
    McpJsonRpcRequest,
)
from foggy.mcp_spi.semantic import DeniedColumn


class MockDimension:
    """Mock dimension for testing time role detection."""

    def __init__(self, is_time=False):
        self._is_time = is_time

    def is_time_dimension(self):
        return self._is_time


class MockModel:
    """Mock query model for testing list_models output."""

    def __init__(self, alias=None, dimensions=None):
        self.alias = alias
        self.dimensions = dimensions or {}


class TestListModelsRpc:
    """Tests for dataset.list_models via MCP RPC handler."""

    @pytest.fixture
    def mock_service(self):
        """Create a mock SemanticQueryService."""
        svc = MagicMock()
        svc.get_all_model_names.return_value = [
            "FactSalesQueryModel",
            "FactOrderQueryModel",
        ]
        svc.get_model.side_effect = lambda name: {
            "FactSalesQueryModel": MockModel(
                alias="销售明细",
                dimensions={"salesDate": MockDimension(is_time=True)},
            ),
            "FactOrderQueryModel": MockModel(
                alias="订单查询",
                dimensions={"orderDate": MockDimension(is_time=True)},
            ),
        }.get(name)
        return svc

    @pytest.fixture
    def router(self, mock_service):
        """Create MCP router with mock service."""
        return create_mcp_router(semantic_service=mock_service)

    @pytest.mark.asyncio
    async def test_list_models_returns_markdown_table(self, mock_service):
        """list_models should return a Markdown table with model info."""
        # Verify the router can be created with our mock service
        router = create_mcp_router(semantic_service=mock_service)
        assert router is not None
        # The router registers routes; the actual list_models handler
        # is invoked via the MCP RPC dispatch, tested at integration level

    @pytest.mark.asyncio
    async def test_list_models_tool_name_accepted(self, mock_service):
        """Both 'list_models' and 'dataset.list_models' should be accepted."""
        # Verify the handler recognizes both name forms
        # This is a structural test of the routing logic
        assert mock_service.get_all_model_names is not None

    @pytest.mark.asyncio
    async def test_list_models_contains_model_names(self, mock_service):
        """Markdown output should contain model names from the service."""
        models = mock_service.get_all_model_names()
        assert "FactSalesQueryModel" in models
        assert "FactOrderQueryModel" in models

    @pytest.mark.asyncio
    async def test_list_models_no_field_index(self, mock_service):
        """list_models output should not contain [field: style indexes."""
        # The Markdown content generated by the handler should never contain
        # field-level indexes - this is a contract requirement
        models = mock_service.get_all_model_names()
        for model_name in models:
            qm = mock_service.get_model(model_name)
            assert qm is not None
            # Verify mock models don't accidentally include field metadata
            assert not hasattr(qm, "fields")

    def test_tool_config_includes_list_models(self):
        """Tool config loader should include dataset.list_models."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = loader.get_tools()
        tool_names = [t.name for t in tools]
        assert "dataset.list_models" in tool_names

    def test_tool_config_includes_compose_script(self):
        """Tool config loader should expose the shared compose script name."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = {t.name: t for t in loader.get_tools()}
        compose_tool = tools.get("dataset.compose_script")
        assert compose_tool is not None
        assert "dataset.compose_script" in compose_tool.description
        assert "dsl({...})" in compose_tool.description
        assert "跨模型 Join / Union" in compose_tool.description
        assert "单模型过滤、分组、聚合、calculatedFields、pivot" in compose_tool.description
        assert "dataset.query_model.payload.pivot" in compose_tool.description
        assert "timeRole=business_date" in compose_tool.description
        assert "timeWindow.field" in compose_tool.description
        assert "不要猜测时间字段" in compose_tool.description
        assert "created_at" in compose_tool.description
        assert "return { plans:" in compose_tool.description
        assert "不要直接 `.execute()`" in compose_tool.description
        assert "Query.from" not in compose_tool.description
        schema = compose_tool.inputSchema
        assert schema.get("properties", {}).get("script", {}).get("type") == "string"
        script_desc = schema.get("properties", {}).get("script", {}).get("description", "")
        assert "dsl({...})" in script_desc
        assert "single-model pivot" in script_desc
        assert "parentShare" in script_desc
        assert "baselineRatio" in script_desc
        assert "return { plans:" in script_desc
        assert ".execute() directly" in script_desc
        assert "Query.from" not in script_desc
        assert "script" in schema.get("required", [])

    def test_query_model_description_points_complex_work_to_compose_script(self):
        """query_model description should keep the single-model boundary clear."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = {t.name: t for t in loader.get_tools()}
        query_tool = tools.get("dataset.query_model")
        assert query_tool is not None
        assert "dataset.compose_script" in query_tool.description
        assert "Join" in query_tool.description
        assert "Union" in query_tool.description
        assert "sum/avg/count(if(...))" in query_tool.description
        assert "description_model" not in query_tool.description
        assert "dataset.describe_model_internal" in query_tool.description

    def test_list_models_schema_is_empty_object(self):
        """list_models schema should be an empty object (no parameters)."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = {t.name: t for t in loader.get_tools()}
        lm_tool = tools.get("dataset.list_models")
        assert lm_tool is not None
        schema = lm_tool.inputSchema
        assert schema.get("type") == "object"
        assert schema.get("properties") == {} or len(schema.get("properties", {})) == 0

    def test_list_models_description_mentions_discover(self):
        """list_models description should mention model discovery purpose."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = {t.name: t for t in loader.get_tools()}
        lm_tool = tools.get("dataset.list_models")
        assert lm_tool is not None
        desc = lm_tool.description.lower()
        # Description should indicate this is for discovering models
        assert "发现" in lm_tool.description or "模型" in lm_tool.description or "list" in desc


class TestListModelsToolClass:
    """Tests for the ListModelsTool BaseMcpTool class in metadata_tool.py."""

    def test_tool_name(self):
        """ListModelsTool.tool_name should be 'list_models'."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool

        assert ListModelsTool.tool_name == "list_models"

    def test_tool_category_is_metadata(self):
        """ListModelsTool.tool_category should be METADATA."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool
        from foggy.mcp_spi.tool import ToolCategory

        assert ListModelsTool.tool_category == ToolCategory.METADATA

    def test_tool_has_no_public_parameters(self):
        """ListModelsTool should remain a no-parameter discovery entry."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool

        tool = ListModelsTool()
        assert tool.get_parameters() == []

    @pytest.mark.asyncio
    async def test_execute_without_service_returns_error(self):
        """Execute without query_service should return error."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool

        tool = ListModelsTool(query_service=None)
        result = await tool.execute({})
        assert result.success is False

    @pytest.mark.asyncio
    async def test_execute_with_service_returns_models(self):
        """Execute with query_service should return model list."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool

        mock_svc = AsyncMock()
        mock_svc.get_available_models = AsyncMock(
            return_value=["ModelA", "ModelB"]
        )

        tool = ListModelsTool(query_service=mock_svc)
        result = await tool.execute({})
        assert result.success is True
        assert result.data["count"] == 2
        assert "ModelA" in result.data["models"]
        assert "ModelB" in result.data["models"]
        assert "items" in result.data


class TestModelCatalogService:
    """Service-level tests for the rich list_models catalog contract."""

    @pytest.fixture
    def catalog_service(self):
        svc = SemanticQueryService()
        svc.register_model(create_fact_sales_model())
        svc.register_model(create_fact_order_model())
        return svc

    def test_catalog_empty_models(self):
        svc = SemanticQueryService()
        catalog = svc.get_model_catalog()
        assert catalog == {
            "models": [],
            "count": 0,
            "recommendedNext": "dataset.describe_model_internal",
            "items": [],
        }
        assert "No data models available" in svc.render_model_catalog_markdown(catalog)

    def test_catalog_json_shape_for_multiple_models(self, catalog_service):
        catalog = catalog_service.get_model_catalog(field_limit=3)
        assert catalog["count"] == 2
        assert catalog["models"] == ["FactSalesModel", "FactOrderModel"]
        assert len(catalog["items"]) == 2
        first = catalog["items"][0]
        assert set(first) >= {
            "model",
            "caption",
            "description",
            "physicalTables",
            "fieldPreview",
            "fieldCount",
        }
        assert "recommendedNext" not in first
        assert len(first["fieldPreview"]) <= 3

    def test_catalog_dedupes_model_names(self, catalog_service):
        catalog = catalog_service.get_model_catalog(
            model_names=["FactSalesModel", "FactSalesModel"],
            field_limit=0,
        )
        assert catalog["models"] == ["FactSalesModel"]
        assert catalog["count"] == 1
        assert len(catalog["items"]) == 1
        assert "fieldPreview" not in catalog["items"][0]
        assert "fieldCount" not in catalog["items"][0]

    def test_catalog_field_preview_is_permission_filtered(self, catalog_service):
        catalog = catalog_service.get_model_catalog(
            model_names=["FactSalesModel"],
            denied_columns=[DeniedColumn(table="fact_sales", column="sales_amount")],
            field_limit=100,
        )
        item = catalog["items"][0]
        assert "salesAmount" not in item["fieldPreview"]
        assert item["fieldCount"] == len(item["fieldPreview"])

    def test_catalog_markdown_rendered_from_json_shape(self, catalog_service):
        catalog = catalog_service.get_model_catalog(
            model_names=["FactSalesModel"],
            llm_hints={
                "FactSalesModel": {
                    "recommendedFor": ["sales analysis"],
                    "notRecommendedFor": ["AR aging"],
                    "keyFields": ["salesAmount"],
                    "businessDateNote": "Use salesDate$id.",
                }
            },
            field_limit=2,
        )
        markdown = catalog_service.render_model_catalog_markdown(catalog)
        assert "FactSalesModel" in markdown
        assert "RecommendedFor:" not in markdown
        assert "NotRecommendedFor:" not in markdown
        assert "KeyFields:" not in markdown
        assert "Business date:" not in markdown
        assert "Field preview:" not in markdown
        assert "dataset.describe_model_internal" not in markdown
        assert "Recommended next:" not in markdown
