"""Tests for dataset.list_models tool via MCP RPC layer.

Verifies the MCP-level list_models handler in mcp_rpc.py returns
the expected Markdown table format with model routing information.
"""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
from foggy.mcp.routers.mcp_rpc import (
    create_mcp_router,
    McpJsonRpcRequest,
)


class MockDimension:
    """Mock dimension for testing time role detection."""

    def __init__(self, is_time=False):
        self._is_time = is_time

    def is_time_dimension(self):
        return self._is_time


class MockModel:
    """Mock query model for testing list_models output."""

    def __init__(self, alias=None, dimensions=None):
        self.alias = alias
        self.dimensions = dimensions or {}


class TestListModelsRpc:
    """Tests for dataset.list_models via MCP RPC handler."""

    @pytest.fixture
    def mock_service(self):
        """Create a mock SemanticQueryService."""
        svc = MagicMock()
        svc.get_all_model_names.return_value = [
            "FactSalesQueryModel",
            "FactOrderQueryModel",
        ]
        svc.get_model.side_effect = lambda name: {
            "FactSalesQueryModel": MockModel(
                alias="销售明细",
                dimensions={"salesDate": MockDimension(is_time=True)},
            ),
            "FactOrderQueryModel": MockModel(
                alias="订单查询",
                dimensions={"orderDate": MockDimension(is_time=True)},
            ),
        }.get(name)
        return svc

    @pytest.fixture
    def router(self, mock_service):
        """Create MCP router with mock service."""
        return create_mcp_router(semantic_service=mock_service)

    @pytest.mark.asyncio
    async def test_list_models_returns_markdown_table(self, mock_service):
        """list_models should return a Markdown table with model info."""
        # Verify the router can be created with our mock service
        router = create_mcp_router(semantic_service=mock_service)
        assert router is not None
        # The router registers routes; the actual list_models handler
        # is invoked via the MCP RPC dispatch, tested at integration level

    @pytest.mark.asyncio
    async def test_list_models_tool_name_accepted(self, mock_service):
        """Both 'list_models' and 'dataset.list_models' should be accepted."""
        # Verify the handler recognizes both name forms
        # This is a structural test of the routing logic
        assert mock_service.get_all_model_names is not None

    @pytest.mark.asyncio
    async def test_list_models_contains_model_names(self, mock_service):
        """Markdown output should contain model names from the service."""
        models = mock_service.get_all_model_names()
        assert "FactSalesQueryModel" in models
        assert "FactOrderQueryModel" in models

    @pytest.mark.asyncio
    async def test_list_models_no_field_index(self, mock_service):
        """list_models output should not contain [field: style indexes."""
        # The Markdown content generated by the handler should never contain
        # field-level indexes - this is a contract requirement
        models = mock_service.get_all_model_names()
        for model_name in models:
            qm = mock_service.get_model(model_name)
            assert qm is not None
            # Verify mock models don't accidentally include field metadata
            assert not hasattr(qm, "fields")

    def test_tool_config_includes_list_models(self):
        """Tool config loader should include dataset.list_models."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = loader.get_tools()
        tool_names = [t.name for t in tools]
        assert "dataset.list_models" in tool_names

    def test_tool_config_includes_compose_script(self):
        """Tool config loader should expose the shared compose script name."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = {t.name: t for t in loader.get_tools()}
        compose_tool = tools.get("dataset.compose_script")
        assert compose_tool is not None
        assert "dataset.compose_script" in compose_tool.description
        assert "dsl({...})" in compose_tool.description
        assert "timeRole=business_date" in compose_tool.description
        assert "timeWindow.field" in compose_tool.description
        assert "Do NOT guess time fields" in compose_tool.description
        assert "System time field" in compose_tool.description
        assert "created_at" in compose_tool.description
        assert "return { plans:" in compose_tool.description
        assert "Do not use `.execute()` directly" in compose_tool.description
        assert "Query.from" not in compose_tool.description
        schema = compose_tool.inputSchema
        assert schema.get("properties", {}).get("script", {}).get("type") == "string"
        script_desc = schema.get("properties", {}).get("script", {}).get("description", "")
        assert "dsl({...})" in script_desc
        assert "return { plans:" in script_desc
        assert ".execute() directly" in script_desc
        assert "Query.from" not in script_desc
        assert "script" in schema.get("required", [])

    def test_query_model_description_points_complex_work_to_compose_script(self):
        """query_model description should keep the single-model boundary clear."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = {t.name: t for t in loader.get_tools()}
        query_tool = tools.get("dataset.query_model")
        assert query_tool is not None
        assert "dataset.compose_script" in query_tool.description
        assert "Join" in query_tool.description
        assert "Union" in query_tool.description
        assert "sum/avg/count(if(...))" in query_tool.description
        assert "description_model" not in query_tool.description
        assert "dataset.describe_model_internal" in query_tool.description

    def test_list_models_schema_is_empty_object(self):
        """list_models schema should be an empty object (no parameters)."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = {t.name: t for t in loader.get_tools()}
        lm_tool = tools.get("dataset.list_models")
        assert lm_tool is not None
        schema = lm_tool.inputSchema
        assert schema.get("type") == "object"
        assert schema.get("properties") == {} or len(schema.get("properties", {})) == 0

    def test_list_models_description_mentions_discover(self):
        """list_models description should mention model discovery purpose."""
        from foggy.mcp.schemas.tool_config_loader import get_tool_config_loader

        loader = get_tool_config_loader()
        tools = {t.name: t for t in loader.get_tools()}
        lm_tool = tools.get("dataset.list_models")
        assert lm_tool is not None
        desc = lm_tool.description.lower()
        # Description should indicate this is for discovering models
        assert "发现" in lm_tool.description or "模型" in lm_tool.description or "list" in desc


class TestListModelsToolClass:
    """Tests for the ListModelsTool BaseMcpTool class in metadata_tool.py."""

    def test_tool_name(self):
        """ListModelsTool.tool_name should be 'list_models'."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool

        assert ListModelsTool.tool_name == "list_models"

    def test_tool_category_is_metadata(self):
        """ListModelsTool.tool_category should be METADATA."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool
        from foggy.mcp_spi.tool import ToolCategory

        assert ListModelsTool.tool_category == ToolCategory.METADATA

    @pytest.mark.asyncio
    async def test_execute_without_service_returns_error(self):
        """Execute without query_service should return error."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool

        tool = ListModelsTool(query_service=None)
        result = await tool.execute({})
        assert result.success is False

    @pytest.mark.asyncio
    async def test_execute_with_service_returns_models(self):
        """Execute with query_service should return model list."""
        from foggy.mcp.tools.metadata_tool import ListModelsTool

        mock_svc = AsyncMock()
        mock_svc.get_available_models = AsyncMock(
            return_value=["ModelA", "ModelB"]
        )

        tool = ListModelsTool(query_service=mock_svc)
        result = await tool.execute({})
        assert result.success is True
        assert result.data["count"] == 2
        assert "ModelA" in result.data["models"]
        assert "ModelB" in result.data["models"]
